# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employeerole'),
        ('project', '0070_auto_20161004_1843'),
        ('invoice', '0003_invoice_management_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name=b'Bank Name')),
                ('account_number', models.CharField(max_length=255, verbose_name=b'Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('micr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('addressline1', models.CharField(blank=True, max_length=255, null=True)),
                ('addressline2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'CompanyBankAccount',
                'verbose_name_plural': 'CompanyBankAccounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(choices=[(b'cheque', b'Cheque'), (b'wire_transfer', b'Wire Transfer'), (b'paypal', b'Paypal')], max_length=50)),
                ('payment_date', models.DateField()),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=1024, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='invoice.CompanyBankAccount')),
            ],
            options={
                'verbose_name': 'PaymentReconciliation',
                'verbose_name_plural': 'PaymentReconciliations',
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('per_fte', 'Per FTE'), ('per_hour', 'Per Hour'), ('per_tx', 'Per Transaction')], max_length=50)),
                ('pricing', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('no_of_txs', models.IntegerField(default=0)),
                ('no_of_resources', models.DecimalField(decimal_places=2, max_digits=5)),
                ('no_of_working_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('no_of_hours', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'ServiceInvoice',
                'verbose_name_plural': 'ServiceInvoices',
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='billing_amount_per_unit',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='billing_type',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='billing_units',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='line_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='filename',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='lead_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.LeadTask'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='no_of_txs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=b'Number of Transactions'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Employee', verbose_name=b'Agent / Artist'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='staff_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.StaffTask'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Task'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='time_in_min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='management_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='invoice.Invoice'),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Service'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='invoice.Invoice'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='service_inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='invoice.ServiceInvoice'),
        ),
    ]
