# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20161216_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=b'invoice_documents/', verbose_name=b'Upload Document'),
        ),
    ]
