# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20160310_1512'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='experienceslab',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='experienceslab',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
