# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_department_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='organization',
        ),
    ]
