# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_employee_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
