# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_delete_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employee.Employee', verbose_name=b'Manager'),
        ),
    ]
