# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20160721_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='roles',
        ),
    ]
