# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_remove_employee_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(b'staff', b'Agent / Artist'), (b'hr', b'HR'), (b'itadmin', b'IT Admin'), (b'lead', b'Lead'), (b'ops_manager', b'Operations Manager'), (b'qc', b'Quality Control'), (b'sales_manager', b'Sales Manager'), (b'sales_rep', b'Sales Representative'), (b'management', b'Management')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Employee')),
            ],
            options={
                'verbose_name': 'EmployeeRole',
                'verbose_name_plural': 'EmployeeRoles',
            },
        ),
    ]
