# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuerterRevenueSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_region', models.IntegerField(blank=True, default=0, null=True)),
                ('yellow_region', models.IntegerField(blank=True, default=0, null=True)),
                ('green_region', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
