# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_customer_services_required'),
        ('project', '0039_auto_20160714_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'ServiceType',
                'verbose_name_plural': 'ServiceTypes',
            },
        ),
        migrations.RemoveField(
            model_name='projectservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='industry',
            name='services',
            field=models.ManyToManyField(to='project.ServiceType'),
        ),
    ]
