# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20160716_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0013_auto_20160721_2051'),
        ('project', '0040_auto_20160714_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_timings', models.CharField(blank=True, choices=[('day', 'Day'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20, null=True)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('statement_of_procedure', models.TextField(blank=True, null=True)),
                ('turn_around_time_in_hours', models.SmallIntegerField(default=0)),
                ('quality', models.SmallIntegerField(default=0)),
                ('number_of_resources', models.SmallIntegerField(default=0)),
                ('billing_interval_in_days', models.SmallIntegerField(default=0)),
                ('amount_per_billing_type', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Pricing')),
                ('billing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BillingType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('operations_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectType')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ServiceType')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='service_documents/', verbose_name='Upload Document')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Service')),
            ],
            options={
                'verbose_name': 'ServiceDocument',
                'verbose_name_plural': 'ServiceDocuments',
            },
        ),
        migrations.CreateModel(
            name='ServiceResourcePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_resources', models.SmallIntegerField(default=0, verbose_name='Number of Resources')),
                ('output_count_per_resource', models.SmallIntegerField(default=0, verbose_name='Output Count')),
                ('experience_slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.ExperienceSlab')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Service')),
            ],
            options={
                'verbose_name': 'Service Resource Plan',
                'verbose_name_plural': 'Service Resource Plan',
            },
        ),
        migrations.CreateModel(
            name='ServiceSla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_value', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Service')),
            ],
            options={
                'verbose_name': 'ServiceSla',
                'verbose_name_plural': 'ServiceSlas',
            },
        ),
        migrations.CreateModel(
            name='Sla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Sla',
                'verbose_name_plural': 'Slas',
            },
        ),
        migrations.AddField(
            model_name='servicesla',
            name='sla_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Sla'),
        ),
    ]
