# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20160721_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='billing_type',
        ),
        migrations.AddField(
            model_name='servicedocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('nda', 'NDA'), ('sla', 'SLA'), ('agreement', 'Agreement'), ('other', 'Other')], max_length=20, null=True, verbose_name='Document Type'),
        ),
    ]
