# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_auto_20160729_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWeekType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('no_of_days', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'WorkWeek Type',
                'verbose_name_plural': 'WorkWeek Types',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Project Detail', 'verbose_name_plural': 'Project Details'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='service',
            name='turn_around_time_in_hours',
        ),
        migrations.AddField(
            model_name='service',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('per_fte', 'per FTE'), ('per_hour', 'per Hour'), ('per_tx', 'per Transaction')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='daily_work_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Operational Hours'),
        ),
        migrations.AddField(
            model_name='service',
            name='fte_cost_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='FTE cost per month'),
        ),
        migrations.AddField(
            model_name='service',
            name='key_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Key Notes'),
        ),
        migrations.AddField(
            model_name='service',
            name='no_of_man_hours_per_month',
            field=models.IntegerField(default=0, verbose_name='Number of man hours per month'),
        ),
        migrations.AddField(
            model_name='service',
            name='projected_prj_value_per_annum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Projected Project Value per annum'),
        ),
        migrations.AddField(
            model_name='service',
            name='projected_prj_value_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Projected Project Value per month'),
        ),
        migrations.AddField(
            model_name='service',
            name='projected_tx_volume_per_day',
            field=models.IntegerField(default=0, verbose_name='Projected Transaction Volume per day'),
        ),
        migrations.AddField(
            model_name='service',
            name='projected_tx_volume_per_month',
            field=models.IntegerField(default=0, verbose_name='Projected Transaction Volume per month'),
        ),
        migrations.AddField(
            model_name='service',
            name='projected_tx_volume_per_week',
            field=models.IntegerField(default=0, verbose_name='Projected Transaction Volume per week'),
        ),
        migrations.AddField(
            model_name='service',
            name='tx_volume_duration_type',
            field=models.CharField(blank=True, choices=[('per_day', 'per Day'), ('per_week', 'per Week'), ('per_month', 'per Month')], max_length=20, null=True, verbose_name='Transaction Volume duration type'),
        ),
        migrations.AddField(
            model_name='service',
            name='workhours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Work Hours End'),
        ),
        migrations.AddField(
            model_name='service',
            name='workhours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Work Hours Start'),
        ),
        migrations.AddField(
            model_name='service',
            name='workweek_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Operational Days'),
        ),
        migrations.AddField(
            model_name='service',
            name='workweek_end',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20, null=True, verbose_name='Work Week End'),
        ),
        migrations.AddField(
            model_name='service',
            name='workweek_start',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20, null=True, verbose_name='Work Week Start'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ServiceType', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='workweek_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.WorkWeekType', verbose_name='Work Week Type'),
        ),
    ]
