# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_auto_20160729_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedocument',
            options={'verbose_name': 'Upload Document', 'verbose_name_plural': 'Upload Documents'},
        ),
        migrations.AlterModelOptions(
            name='serviceresourceplan',
            options={'verbose_name': 'Resource Plan', 'verbose_name_plural': 'Resource Plan'},
        ),
        migrations.AlterField(
            model_name='servicesla',
            name='sla_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Sla', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='servicesla',
            name='sla_value',
            field=models.CharField(max_length=255, verbose_name='Metrics'),
        ),
    ]
