# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employeerole'),
        ('project', '0044_auto_20160729_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('filename', models.FilePathField(blank=True, max_length=1024, null=True)),
                ('no_of_txs', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Transactions')),
                ('no_of_txs_completed', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Transactions completed')),
                ('total_time_hours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Employee')),
            ],
            options={
                'verbose_name': 'Lead Task',
                'verbose_name_plural': 'Lead Tasks',
            },
        ),
        migrations.CreateModel(
            name='LeadTaskResourcePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_resources', models.SmallIntegerField(default=0, verbose_name='Number of Resources')),
                ('output_count_per_resource', models.SmallIntegerField(default=0, verbose_name='Output Count')),
                ('experience_slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.ExperienceSlab')),
                ('lead_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.LeadTask')),
            ],
            options={
                'verbose_name': 'Lead Task Resource Plan',
                'verbose_name_plural': 'Lead Task Resource Plan',
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('filename', models.FilePathField(blank=True, max_length=1024, null=True)),
                ('no_of_txs', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Transactions')),
                ('no_of_txs_completed', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Transactions completed')),
                ('total_time_hours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('lead_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.LeadTask')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Employee', verbose_name='Agent / Artist')),
            ],
            options={
                'verbose_name': 'Agent / Artist Task',
                'verbose_name_plural': 'Agent / Artist Tasks',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('title', models.CharField(max_length=255)),
                ('folderpath', models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1024, null=True)),
                ('no_of_txs', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Transactions')),
                ('no_of_txs_completed', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Transactions completed')),
                ('total_time_hours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('custom_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field3', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field4', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field5', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field6', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field7', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field8', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field9', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field10', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Service')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskResourcePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_resources', models.SmallIntegerField(default=0, verbose_name='Number of Resources')),
                ('output_count_per_resource', models.SmallIntegerField(default=0, verbose_name='Output Count')),
                ('experience_slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.ExperienceSlab')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Task')),
            ],
            options={
                'verbose_name': 'Resource Plan',
                'verbose_name_plural': 'Resource Plan',
            },
        ),
        migrations.AddField(
            model_name='leadtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Task'),
        ),
    ]
