# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20160729_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field4_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field5_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field6_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field7_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field8_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field9_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field10_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field1_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field2_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field3_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field4_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field5_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field6_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field7_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field8_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field9_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field10_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field1_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field2_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field3_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field4_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field5_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field6_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field7_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field8_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field9_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('custom_field10_datatype', models.CharField(blank=True, choices=[('INTEGER', 'INTEGER'), ('STRING', 'STRING'), ('DATE', 'DATE'), ('DATETME', 'DATETIME'), ('DECIMAL', 'DECIMAL')], max_length=30, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Service')),
            ],
        ),
    ]
