# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employeerole'),
        ('project', '0046_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='error_percent',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='is_qc_required',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='qc_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Employee', verbose_name='QC Lead'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='qc_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], max_length=20, null=True, verbose_name='QC Status'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='time_in_min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
