# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_qctemplate_stafftaskqc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadtask',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='stafftask',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='task',
            name='folderpath',
        ),
    ]
