# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_auto_20160806_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtask',
            name='filename',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='filename',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='task',
            name='folderpath',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=b''),
        ),
    ]
