# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_auto_20160809_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='custom_field1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field10',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field3',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field4',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field5',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field6',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field7',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field8',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_field9',
        ),
        migrations.AddField(
            model_name='leadtask',
            name='filename',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='filename',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='folderpath',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
