# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employeerole'),
        ('project', '0054_auto_20160809_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignServiceLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Service')),
            ],
            options={
                'verbose_name': 'Assign Lead To Service',
                'verbose_name_plural': 'Assign Lead To Service',
            },
        ),
        migrations.AddField(
            model_name='leadtask',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='new', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='new', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='new', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Service', verbose_name='Project Detail'),
        ),
    ]
