# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_stafftask_time_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='error_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='no_of_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], default=0),
        ),
    ]
