# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_auto_20160818_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='project',
        ),
        migrations.AddField(
            model_name='service',
            name='encrypt_fte_cost_per_month',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='encrypt_pricing',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='encrypt_projected_prj_value_per_annum',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='encrypt_projected_prj_value_per_month',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
