# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_auto_20160830_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')]),
        ),
    ]
