# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_auto_20160830_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
    ]
