# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_servicedocument_other_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedocument',
            name='share_with_others',
            field=models.NullBooleanField(default=False, verbose_name='Share with others'),
        ),
    ]
