# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_auto_20160916_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='is_workedon',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='billingtype',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='projecttype',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='servicetype',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='sla',
            unique_together=set([('title',)]),
        ),
    ]
