# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0069_auto_20161004_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadtask',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('qc', 'Quality Check')], default='new', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='qc_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], max_length=20, null=True, verbose_name='QC Status'),
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('qc', 'Quality Check')], default='new', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('qc', 'Quality Check')], default='new', max_length=20, null=True),
        ),
    ]
