# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_auto_20161004_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='oa_experiance_slab',
            field=models.TextField(default=True),
        ),
    ]
