# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('client_local_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_global_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=8)),
                ('title_loc', models.CharField(max_length=1024)),
                ('title_eng', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('level', models.IntegerField(choices=[(1, b'Debug'), (2, b'Info'), (3, b'Warning'), (4, b'Error'), (5, b'Critical')], default=1)),
                ('text', models.CharField(max_length=1024)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhouseapp.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_username', models.CharField(blank=True, max_length=30, null=True)),
                ('user_is_staff', models.BooleanField(default=False)),
                ('user_is_active', models.BooleanField(default=False)),
                ('client_name', models.CharField(blank=True, max_length=512, null=True)),
                ('client_local_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_global_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('server_name', models.CharField(blank=True, max_length=512, null=True)),
                ('server_host', models.CharField(blank=True, max_length=512, null=True)),
                ('scheme', models.CharField(blank=True, max_length=16, null=True)),
                ('method', models.CharField(blank=True, max_length=16, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('is_ajax', models.BooleanField(default=False)),
                ('from_page', models.CharField(blank=True, max_length=1024, null=True)),
                ('to_page', models.CharField(blank=True, max_length=1024, null=True)),
                ('to_page_query', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=1024)),
                ('group', models.CharField(blank=True, default=b'', max_length=128, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='settings',
            unique_together=set([('key', 'group')]),
        ),
    ]
