# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20160714_1949'),
        ('customer', '0011_remove_customer_services_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='services',
            field=models.ManyToManyField(related_name='_customer_services_+', to='project.ServiceType', verbose_name='Services Required'),
        ),
        migrations.AddField(
            model_name='lead',
            name='services',
            field=models.ManyToManyField(related_name='_lead_services_+', to='project.ServiceType', verbose_name='Services Required'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Industry'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.Industry'),
        ),
    ]
