# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20160714_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'CurrencyType',
                'verbose_name_plural': 'CurrencyTypes',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CurrencyType'),
        ),
        migrations.AddField(
            model_name='lead',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CurrencyType'),
        ),
    ]
