# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20160716_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='is_converted_to_customer',
            field=models.BooleanField(default=False, verbose_name='Converted'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_followup',
            field=models.DateField(blank=True, null=True),
        ),
    ]
