# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20160725_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='latest_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='latest_lead_status',
            field=models.CharField(blank=True, choices=[('COLD', 'Cold'), ('WARM', 'Warm'), ('HOT', 'Hot')], max_length=20),
        ),
    ]
