# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20160811_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='currency',
        ),
    ]
