# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='latest_lead_status',
            field=models.CharField(blank=True, choices=[('COLD', 'Cold'), ('WARM', 'Warm'), ('HOT', 'Hot')], max_length=20, null=True),
        ),
    ]
