# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20160922_1012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='currencytype',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set([('title',)]),
        ),
    ]
