# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20160929_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_invoice_no',
            field=models.IntegerField(default=0),
        ),
    ]
