# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20161229_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
